url: https://embedded-for-her.github.io
baseurl: https://embedded-for-her.github.io/

# Site settings
title: Embedded for Her
email: p@earthlord.io
description: "Embedded for Her is a skill development program in the field of embedded systems for women."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: B7ACC2
  secondary: 4c177d
  secondary-dark: 333

# Team names, titles and social links
people:
- name: WorkBench Projects
  pic: WP.png
  position: 
  social:
    - title: globe
      url: http://workbenchprojects.com/
    - title: facebook
      url: https://www.facebook.com/workbenchprojects/
    - title: twitter
      url: https://twitter.com/makewithWP
    - title: maxcdn
      url: http://www.meetup.com/Workbench-Projects/

- name: IoTBLR
  pic: IoTBLR.png
  position: 
  social:
    - title: globe
      url: http://iotblr.org/
    - title: facebook
      url: https://www.facebook.com/groups/IoTBLR/
    - title: twitter
      url: https://twitter.com/IoTBLR
    - title: maxcdn
      url: http://www.meetup.com/IoTBLR/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
